//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class INETResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal INETResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INETResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El password es incorrecto o el nuevo password no es válido..
        /// </summary>
        internal static string ChangePassword_Error {
            get {
                return ResourceManager.GetString("ChangePassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se modificó la contraseña con éxito..
        /// </summary>
        internal static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder continuar debe cargar un adjunto al plan con la documentación correspondiente..
        /// </summary>
        internal static string ChangeStatusNoAttachment_Error {
            get {
                return ResourceManager.GetString("ChangeStatusNoAttachment_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar modificar el estado. No se registran solicitados en el plan..
        /// </summary>
        internal static string ChangeStatusNoSolicitudes_Error {
            get {
                return ResourceManager.GetString("ChangeStatusNoSolicitudes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar modificar el estado. Es posible que otro usuario haya modificado el estado antes que usted o que falte información en los registros para continuar..
        /// </summary>
        internal static string ChangeStatus_Error {
            get {
                return ResourceManager.GetString("ChangeStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se modificó el estado con éxito..
        /// </summary>
        internal static string ChangeStatus_Success {
            get {
                return ResourceManager.GetString("ChangeStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible modificar el CUE debido a que ya existen solicitados asociados al plan..
        /// </summary>
        internal static string CUE_CannotChangeCUE {
            get {
                return ResourceManager.GetString("CUE_CannotChangeCUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Eje seleccionado no es válido para el CUE ingresado..
        /// </summary>
        internal static string CUE_FieldNotValid {
            get {
                return ResourceManager.GetString("CUE_FieldNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Línea seleccionada no es válido para el CUE ingresado..
        /// </summary>
        internal static string CUE_LineNotValid {
            get {
                return ResourceManager.GetString("CUE_LineNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CUE ingresado no es válido..
        /// </summary>
        internal static string CUE_NotValidCUE {
            get {
                return ResourceManager.GetString("CUE_NotValidCUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de plan no es válido para el CUE..
        /// </summary>
        internal static string CUE_NotValidPlanTypeForCUE {
            get {
                return ResourceManager.GetString("CUE_NotValidPlanTypeForCUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay uno o mas numeros de expediente repetidos..
        /// </summary>
        internal static string FileNumbers_Are_Repeated {
            get {
                return ResourceManager.GetString("FileNumbers_Are_Repeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso no permitido.
        /// </summary>
        internal static string Forbiden {
            get {
                return ResourceManager.GetString("Forbiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mail ingresado no pertenece a un usuario registrado en el sistema.
        /// </summary>
        internal static string ForgotPassword_Error {
            get {
                return ResourceManager.GetString("ForgotPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se le ha enviado un email con las instrucciones para cambiar su contraseña..
        /// </summary>
        internal static string ForgotPassword_Sucess {
            get {
                return ResourceManager.GetString("ForgotPassword_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió el siguiente error al intentar importar los solicitados: {0}.
        /// </summary>
        internal static string Import_Solicitudes_Error {
            get {
                return ResourceManager.GetString("Import_Solicitudes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se importaron los solicitados con éxito..
        /// </summary>
        internal static string Import_Solicitudes_Success {
            get {
                return ResourceManager.GetString("Import_Solicitudes_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al querer anular el plan..
        /// </summary>
        internal static string ImprovementPlan_Block_Error {
            get {
                return ResourceManager.GetString("ImprovementPlan_Block_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El plan se anuló con éxito..
        /// </summary>
        internal static string ImprovementPlan_Block_Success {
            get {
                return ResourceManager.GetString("ImprovementPlan_Block_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cambiar el Tipo de Plan ya que tiene Solicitados asociados al mismo..
        /// </summary>
        internal static string ImprovementPlan_CantChangeType {
            get {
                return ResourceManager.GetString("ImprovementPlan_CantChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El plan {0} se eliminó con éxito..
        /// </summary>
        internal static string ImprovementPlan_Delete {
            get {
                return ResourceManager.GetString("ImprovementPlan_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar el plan {0}..
        /// </summary>
        internal static string ImprovementPlan_Delete_Error {
            get {
                return ResourceManager.GetString("ImprovementPlan_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe cargar el XLS del PLan ingresado..
        /// </summary>
        internal static string ImprovementPlan_DocumentationRequired {
            get {
                return ResourceManager.GetString("ImprovementPlan_DocumentationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Eje no es válido para el usuario..
        /// </summary>
        internal static string ImprovementPlan_InvalidUserField {
            get {
                return ResourceManager.GetString("ImprovementPlan_InvalidUserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CUE no pertenece a una provincia del usuario..
        /// </summary>
        internal static string ImprovementPlan_InvalidUserProvince {
            get {
                return ResourceManager.GetString("ImprovementPlan_InvalidUserProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posee permisos para poder visualizar el plan..
        /// </summary>
        internal static string ImprovementPlan_NoPermissions {
            get {
                return ResourceManager.GetString("ImprovementPlan_NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar uno o más solicitados a modificar..
        /// </summary>
        internal static string ImprovementPlan_NoSolicitudesSelected {
            get {
                return ResourceManager.GetString("ImprovementPlan_NoSolicitudesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de plan solicitado no existe..
        /// </summary>
        internal static string ImprovementPlan_NotExists {
            get {
                return ResourceManager.GetString("ImprovementPlan_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El plan de mejora {0} se guardó con éxito..
        /// </summary>
        internal static string ImprovementPlan_Save {
            get {
                return ResourceManager.GetString("ImprovementPlan_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se {0} {1} de {2} solicitados..
        /// </summary>
        internal static string ImprovementPlan_SolicitudeActionResult {
            get {
                return ResourceManager.GetString("ImprovementPlan_SolicitudeActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible guardar la incidencia debido a que la misma no es válida..
        /// </summary>
        internal static string Incidences_Save_Error {
            get {
                return ResourceManager.GetString("Incidences_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La incidencia se guardó con éxito..
        /// </summary>
        internal static string Incidences_Save_Success {
            get {
                return ResourceManager.GetString("Incidences_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos ingresados no son válidos.
        /// </summary>
        internal static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o la contraseña ingresada no son válidas.
        /// </summary>
        internal static string Login_InvalidLogin {
            get {
                return ResourceManager.GetString("Login_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede generar el reporte.
        /// </summary>
        internal static string ReportsBuildError {
            get {
                return ResourceManager.GetString("ReportsBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible cambiar su contraseña. Verifique que los datos ingresados sean válidos y que no haya caducado el período de tiempo válido para cambiar su contraseña.
        /// </summary>
        internal static string ResetPassword_Error {
            get {
                return ResourceManager.GetString("ResetPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar la disposición.
        /// </summary>
        internal static string Resolution_Save_Error {
            get {
                return ResourceManager.GetString("Resolution_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La disposición se guardó con éxito.
        /// </summary>
        internal static string Resolution_Save_Success {
            get {
                return ResourceManager.GetString("Resolution_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo actualizar el Rol y sus permisos.
        /// </summary>
        internal static string Roles_Error {
            get {
                return ResourceManager.GetString("Roles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos ingresados no son válidos..
        /// </summary>
        internal static string Roles_Invalid {
            get {
                return ResourceManager.GetString("Roles_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol se actualizó con éxito..
        /// </summary>
        internal static string Roles_Save_Success {
            get {
                return ResourceManager.GetString("Roles_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar el solicitado debido a que tiene incidencias relacionadas.
        /// </summary>
        internal static string Solicitudes_Delete_IncidencesRelated {
            get {
                return ResourceManager.GetString("Solicitudes_Delete_IncidencesRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El solicitado se eliminó con éxito..
        /// </summary>
        internal static string Solicitudes_Delete_Success {
            get {
                return ResourceManager.GetString("Solicitudes_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible guardar el solicitado debido a que el mismo no es válido..
        /// </summary>
        internal static string Solicitudes_Save_Error {
            get {
                return ResourceManager.GetString("Solicitudes_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El solicitado se guardó con éxito..
        /// </summary>
        internal static string Solicitudes_Save_Success {
            get {
                return ResourceManager.GetString("Solicitudes_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó la plantilla con éxito.
        /// </summary>
        internal static string Templates_Delete_Success {
            get {
                return ResourceManager.GetString("Templates_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El template no es válido. Asegúrese de que contenga las pabras clave [CUERPO] y [FIRMA] (cuando corresponda)..
        /// </summary>
        internal static string Templates_NotValid {
            get {
                return ResourceManager.GetString("Templates_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La plantilla se guardó con éxito..
        /// </summary>
        internal static string Templates_Save_Success {
            get {
                return ResourceManager.GetString("Templates_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar la plantilla seleccionada..
        /// </summary>
        internal static string Template_Delete_Error {
            get {
                return ResourceManager.GetString("Template_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar guardar la plantilla.
        /// </summary>
        internal static string Template_Error {
            get {
                return ResourceManager.GetString("Template_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar el usuario debido a que el mismo ya ha utilizado el sistema o es el usuario con el que se encuentra logueado..
        /// </summary>
        internal static string Users_CantDeleteUser {
            get {
                return ResourceManager.GetString("Users_CantDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se eliminó con éxito..
        /// </summary>
        internal static string Users_Delete_Success {
            get {
                return ResourceManager.GetString("Users_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos ingresados no son válidos..
        /// </summary>
        internal static string Users_Error {
            get {
                return ResourceManager.GetString("Users_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se guardó con éxito..
        /// </summary>
        internal static string Users_Save_Success {
            get {
                return ResourceManager.GetString("Users_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} ya existe en el sistema..
        /// </summary>
        internal static string Users_UserAlreadyExist {
            get {
                return ResourceManager.GetString("Users_UserAlreadyExist", resourceCulture);
            }
        }
    }
}
