//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRendering
    {
        public int AccountingRenderingID { get; set; }
        public string Number { get; set; }
        public Nullable<int> DictumId { get; set; }
        public int ExpenditureObjectTypeId { get; set; }
        public int ImprovementPlanId { get; set; }
        public decimal AprovedAmount { get; set; }
        public System.DateTime Date { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> RejectedAmount { get; set; }
    
        public virtual Dictum Dictum { get; set; }
        public virtual ExpenditureObjectType ExpenditureObjectType { get; set; }
        public virtual ImprovementPlan ImprovementPlan { get; set; }
    }
}
