//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int EntityId { get; set; }
        public string EntityName { get; set; }
        public string PropertyName { get; set; }
        public string AdditionalData { get; set; }
        public string Action { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string OriginalValue { get; set; }
        public string CurrentValue { get; set; }
        public Nullable<int> ImprovementPlanId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
