//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budgets_216
    {
        public int Id { get; set; }
        public int SchoolYearId { get; set; }
        public int ProvinceId { get; set; }
        public int FieldId { get; set; }
        public int LineId { get; set; }
        public Nullable<decimal> Ammount { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual SubField SubField { get; set; }
        public virtual Lines_22 Lines_22 { get; set; }
    }
}
