//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Incidences = new HashSet<Incidence>();
            this.Solicitudes = new HashSet<Solicitude>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IncludeInDictum { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual ICollection<Incidence> Incidences { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
    }
}
