//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictum : Document
    {
        public Dictum()
        {
            this.Solicitudes = new HashSet<Solicitude>();
            this.Resolutions = new HashSet<Resolution>();
            this.AccountRenderings = new HashSet<AccountRendering>();
        }
    
        public Nullable<int> EligibilityStatusId { get; set; }
        public Nullable<decimal> Ammount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int Number { get; set; }
        public bool EligibilityRequired { get; set; }
        public string EligibilityExternalNumber { get; set; }
        public string ElegibilityExternalEntity { get; set; }
        public string FileNumber { get; set; }
        public bool Locked { get; set; }
        public string DictumNumber { get; set; }
    
        public virtual Status EligibilityStatus { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
        public virtual ICollection<Resolution> Resolutions { get; set; }
        public virtual ICollection<AccountRendering> AccountRenderings { get; set; }
    }
}
