//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentVariables = new HashSet<DocumentVariable>();
        }
    
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int TemplateId { get; set; }
        public Nullable<System.DateTime> EmissionDate { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string Body { get; set; }
        public string PDF { get; set; }
        public Nullable<int> ImprovementPlanId { get; set; }
        public int CreationUserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string UserBody { get; set; }
        public string SignedDocument { get; set; }
        public string PDF_Annex { get; set; }
        public string PDF_Annex_extra { get; set; }
        public string AnnexDocument { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Template Template { get; set; }
        public virtual ImprovementPlan ImprovementPlan { get; set; }
        public virtual UserProfile CreationUser { get; set; }
        public virtual ICollection<DocumentVariable> DocumentVariables { get; set; }
    }
}
