//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVariable
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public string Text { get; set; }
        public int TemplateVariableId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual TemplateVariable TemplateVariable { get; set; }
    }
}
