//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Budgets = new HashSet<Budget>();
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Lines = new HashSet<Line>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.Templates = new HashSet<Template>();
            this.SubFields = new HashSet<SubField>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Management { get; set; }
        public string Code { get; set; }
        public int StatusId { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<SubField> SubFields { get; set; }
    }
}
