//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImprovementPlan
    {
        public ImprovementPlan()
        {
            this.ImprovementPlans1 = new HashSet<ImprovementPlan>();
            this.Incidences = new HashSet<Incidence>();
            this.Solicitudes = new HashSet<Solicitude>();
            this.Comments = new HashSet<Comment>();
            this.Documents = new HashSet<Document>();
            this.RelatedLines_22 = new HashSet<RelatedLines_22>();
            this.AccountRenderings = new HashSet<AccountRendering>();
        }
    
        public int Id { get; set; }
        public int ImprovementPlanTypeId { get; set; }
        public int FieldId { get; set; }
        public int StatusId { get; set; }
        public int SchoolYearId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Identifier { get; set; }
        public string CUE { get; set; }
        public System.DateTime ReceptionDate { get; set; }
        public string Summary { get; set; }
        public Nullable<int> EvaluatorUserId { get; set; }
        public Nullable<System.DateTime> FieldDate { get; set; }
        public string InstitutionName { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string Attachment { get; set; }
        public string Documentation { get; set; }
        public string InstitutionLevel { get; set; }
        public Nullable<int> InstitutionLevelInt { get; set; }
        public string Dependence { get; set; }
        public string Articulator { get; set; }
        public string ArticulatorExp { get; set; }
        public string AttachmentAdd { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<int> SubFieldId { get; set; }
        public Nullable<int> Line_22_Id { get; set; }
        public Nullable<bool> Pronafe { get; set; }
        public Nullable<int> ArticulatorLineId { get; set; }
        public Nullable<int> ArticulatorImprovementPlanId { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans1 { get; set; }
        public virtual ImprovementPlan Parent { get; set; }
        public virtual ImprovementPlansType ImprovementPlansType { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Incidence> Incidences { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Line Line { get; set; }
        public virtual Lines_22 Lines_22 { get; set; }
        public virtual SubField SubField { get; set; }
        public virtual ICollection<RelatedLines_22> RelatedLines_22 { get; set; }
        public virtual ICollection<AccountRendering> AccountRenderings { get; set; }
    }
}
