//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidence
    {
        public Incidence()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int ImprovementPlanId { get; set; }
        public Nullable<int> SolicitudeId { get; set; }
        public int UserId { get; set; }
        public int IncidentTypeId { get; set; }
        public System.DateTime Date { get; set; }
        public bool Active { get; set; }
        public string Details { get; set; }
    
        public virtual ImprovementPlan ImprovementPlan { get; set; }
        public virtual IncidenceType IncidenceType { get; set; }
        public virtual Solicitude Solicitude { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
