//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INETContext : DbContext
    {
        public INETContext()
            : base("name=INETContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Audit> Audits { get; set; }
        public DbSet<Budget> Budgets { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<DictumType> DictumTypes { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<ExpenditureType> ExpenditureTypes { get; set; }
        public DbSet<Field> Fields { get; set; }
        public DbSet<FileNumber> FileNumbers { get; set; }
        public DbSet<ImprovementPlan> ImprovementPlans { get; set; }
        public DbSet<ImprovementPlansType> ImprovementPlansTypes { get; set; }
        public DbSet<Incidence> Incidences { get; set; }
        public DbSet<IncidenceType> IncidenceTypes { get; set; }
        public DbSet<Institution> Institutions { get; set; }
        public DbSet<Line> Lines { get; set; }
        public DbSet<MeasurementUnit> MeasurementUnits { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<SchoolYear> SchoolYears { get; set; }
        public DbSet<Solicitude> Solicitudes { get; set; }
        public DbSet<SolicitudeType> SolicitudeTypes { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<StatusCriterion> StatusCriterions { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<TemplateTypeField> TemplateTypeFields { get; set; }
        public DbSet<TemplateType> TemplateTypes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<TemplateTypeBlock> TemplateTypeBlocks { get; set; }
        public DbSet<DocumentVariable> DocumentVariables { get; set; }
        public DbSet<TemplateVariable> TemplateVariables { get; set; }
        public DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public DbSet<InstitutionLevel> InstitutionLevels { get; set; }
        public DbSet<webpages_Permissions> webpages_Permissions { get; set; }
        public DbSet<webpages_RolePermissionStatuses> webpages_RolePermissionStatuses { get; set; }
        public DbSet<Lines_22> Lines_22 { get; set; }
        public DbSet<SubField> SubFields { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Documents_TMP> Documents_TMP { get; set; }
        public DbSet<ExpenditureObjectType> ExpenditureObjectTypes { get; set; }
        public DbSet<Budgets_216> Budgets_216 { get; set; }
        public DbSet<RelatedLines_22> RelatedLines_22 { get; set; }
        public DbSet<AccountRendering> AccountRenderings { get; set; }
    }
}
