//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int Id { get; set; }
        public string Province { get; set; }
        public string Department { get; set; }
        public string Locality { get; set; }
        public string Scope { get; set; }
        public string Orientation { get; set; }
        public string InstitutionType { get; set; }
    }
}
