//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lines_22
    {
        public Lines_22()
        {
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Solicitudes = new HashSet<Solicitude>();
            this.Budgets_216 = new HashSet<Budgets_216>();
            this.RelatedLines_22 = new HashSet<RelatedLines_22>();
        }
    
        public int Id { get; set; }
        public int SubFieldId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public int LineId { get; set; }
        public string title_xls { get; set; }
    
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual SubField SubField { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
        public virtual Line Line { get; set; }
        public virtual ICollection<Budgets_216> Budgets_216 { get; set; }
        public virtual ICollection<RelatedLines_22> RelatedLines_22 { get; set; }
    }
}
