//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.Budgets = new HashSet<Budget>();
            this.Solicitudes = new HashSet<Solicitude>();
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Lines_22 = new HashSet<Lines_22>();
        }
    
        public int Id { get; set; }
        public int FieldId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string title_xls { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual Field Field { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual ICollection<Lines_22> Lines_22 { get; set; }
    }
}
