//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedLines_22
    {
        public int Id { get; set; }
        public Nullable<int> ImprovementPlanId { get; set; }
        public Nullable<int> Line22Id { get; set; }
        public string CUE { get; set; }
        public Nullable<int> ImprovementPlanId_Link { get; set; }
    
        public virtual ImprovementPlan ImprovementPlan { get; set; }
        public virtual Lines_22 Lines_22 { get; set; }
    }
}
