//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resolution : Document
    {
        public Resolution()
        {
            this.Dictums = new HashSet<Dictum>();
        }
    
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ProtocolizedDate { get; set; }
        public Nullable<decimal> AmountExecuted { get; set; }
        public string Annex { get; set; }
        public int Number { get; set; }
        public string ResolutionNumber { get; set; }
        public Nullable<System.DateTime> AnnexSignatureDate { get; set; }
    
        public virtual ICollection<Dictum> Dictums { get; set; }
    }
}
