//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolYear
    {
        public SchoolYear()
        {
            this.Budgets = new HashSet<Budget>();
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Solicitudes = new HashSet<Solicitude>();
            this.Budgets_216 = new HashSet<Budgets_216>();
        }
    
        public int Id { get; set; }
        public string Cycle { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
        public virtual ICollection<Budgets_216> Budgets_216 { get; set; }
    }
}
