//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitude
    {
        public Solicitude()
        {
            this.Incidences = new HashSet<Incidence>();
            this.Comments = new HashSet<Comment>();
            this.Dictums = new HashSet<Dictum>();
        }
    
        public int Id { get; set; }
        public int SchoolYearId { get; set; }
        public int MeasurementUnitId { get; set; }
        public Nullable<int> SolicitudeTypeId { get; set; }
        public Nullable<int> ExpenditureTypeId { get; set; }
        public int StatusId { get; set; }
        public int ImprovementPlanId { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<int> ReassignedId { get; set; }
        public string CUE { get; set; }
        public string Details { get; set; }
        public string FileNumber { get; set; }
        public string Specialization { get; set; }
        public Nullable<decimal> RequestedAmount { get; set; }
        public Nullable<decimal> RequestedPriceUnit { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<decimal> ApprovedPriceUnit { get; set; }
        public bool Locked { get; set; }
        public Nullable<decimal> ReassignedRequestedTotal { get; set; }
        public Nullable<decimal> ReassignedGrantedTotal { get; set; }
        public string Level { get; set; }
        public string Management { get; set; }
        public Nullable<int> Line_22_Id { get; set; }
        public Nullable<int> Field_Id { get; set; }
        public Nullable<int> SubField_Id { get; set; }
        public Nullable<int> ExpenditureObjectTypeId { get; set; }
    
        public virtual ExpenditureType ExpenditureType { get; set; }
        public virtual ImprovementPlan ImprovementPlan { get; set; }
        public virtual ICollection<Incidence> Incidences { get; set; }
        public virtual Line Line { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual SolicitudeType SolicitudeType { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Dictum> Dictums { get; set; }
        public virtual Solicitude Reasigned { get; set; }
        public virtual Solicitude SolicitudeRelationship { get; set; }
        public virtual Lines_22 Lines_22 { get; set; }
        public virtual ExpenditureObjectType ExpenditureObjectType { get; set; }
    }
}
