//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Dictums = new HashSet<Dictum>();
            this.Documents = new HashSet<Document>();
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Solicitudes = new HashSet<Solicitude>();
            this.Fields = new HashSet<Field>();
            this.webpages_RolePermissionStatuses = new HashSet<webpages_RolePermissionStatuses>();
            this.SubFields = new HashSet<SubField>();
        }
    
        public int Id { get; set; }
        public int StatusCriterionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Dictum> Dictums { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual ICollection<Solicitude> Solicitudes { get; set; }
        public virtual StatusCriterion StatusCriterion { get; set; }
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<webpages_RolePermissionStatuses> webpages_RolePermissionStatuses { get; set; }
        public virtual ICollection<SubField> SubFields { get; set; }
    }
}
