//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCriterion
    {
        public StatusCriterion()
        {
            this.Status = new HashSet<Status>();
            this.webpages_Permissions = new HashSet<webpages_Permissions>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Status> Status { get; set; }
        public virtual ICollection<webpages_Permissions> webpages_Permissions { get; set; }
    }
}
