//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateTypeVariable
    {
        public TemplateTypeVariable()
        {
            this.DocumentVariables = new HashSet<DocumentVariable>();
        }
    
        public int Id { get; set; }
        public int TemplateTypeId { get; set; }
        public string Variable { get; set; }
    
        public virtual ICollection<DocumentVariable> DocumentVariables { get; set; }
        public virtual TemplateType TemplateType { get; set; }
    }
}
