//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateType
    {
        public TemplateType()
        {
            this.Templates = new HashSet<Template>();
            this.TemplateTypeFields = new HashSet<TemplateTypeField>();
            this.TemplateTypeBlocks = new HashSet<TemplateTypeBlock>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public bool Eligibility { get; set; }
    
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<TemplateTypeField> TemplateTypeFields { get; set; }
        public virtual ICollection<TemplateTypeBlock> TemplateTypeBlocks { get; set; }
    }
}
