//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateVariable
    {
        public TemplateVariable()
        {
            this.DocumentVariables = new HashSet<DocumentVariable>();
        }
    
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public string Variable { get; set; }
    
        public virtual ICollection<DocumentVariable> DocumentVariables { get; set; }
        public virtual Template Template { get; set; }
    }
}
