//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.Documents = new HashSet<Document>();
            this.TemplateVariables = new HashSet<TemplateVariable>();
            this.Fields = new HashSet<Field>();
        }
    
        public int Id { get; set; }
        public int TemplateTypeId { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Content { get; set; }
        public Nullable<double> marginLeft { get; set; }
        public Nullable<double> marginRight { get; set; }
        public Nullable<double> marginTop { get; set; }
        public Nullable<double> marginBottom { get; set; }
        public string Header { get; set; }
        public string SignatureImagePath { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual TemplateType TemplateType { get; set; }
        public virtual ICollection<TemplateVariable> TemplateVariables { get; set; }
        public virtual ICollection<Field> Fields { get; set; }
    }
}
