//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateTypeField
    {
        public int Id { get; set; }
        public int TemplateTypeId { get; set; }
        public string Field { get; set; }
        public string Description { get; set; }
    
        public virtual TemplateType TemplateType { get; set; }
    }
}
