//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Audits = new HashSet<Audit>();
            this.Comments = new HashSet<Comment>();
            this.ImprovementPlans = new HashSet<ImprovementPlan>();
            this.Incidences = new HashSet<Incidence>();
            this.Fields = new HashSet<Field>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.Documents = new HashSet<Document>();
            this.Provinces = new HashSet<Province>();
            this.InstitutionLevels = new HashSet<InstitutionLevel>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Province_Id { get; set; }
    
        public virtual ICollection<Audit> Audits { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<ImprovementPlan> ImprovementPlans { get; set; }
        public virtual ICollection<Incidence> Incidences { get; set; }
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
        public virtual ICollection<InstitutionLevel> InstitutionLevels { get; set; }
    }
}
