//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_Permissions
    {
        public webpages_Permissions()
        {
            this.StatusCriterions = new HashSet<StatusCriterion>();
            this.webpages_RolePermissionStatuses = new HashSet<webpages_RolePermissionStatuses>();
        }
    
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public string PermissionCode { get; set; }
    
        public virtual ICollection<StatusCriterion> StatusCriterions { get; set; }
        public virtual ICollection<webpages_RolePermissionStatuses> webpages_RolePermissionStatuses { get; set; }
    }
}
