//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INET.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_RolePermissionStatuses
    {
        public int Id { get; set; }
        public int PermissionId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual webpages_Permissions webpages_Permissions { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
    }
}
